GET http://localhost:8000/api/usuarios

###                                                 COBRADORES ENDPOINTS 

###     OBTENER TODOS LOS COBRADORES
GET http://localhost:8000/api/cobradores

###     CREAR REGISTRO COBRADOR
POST http://localhost:8000/api/cobradores
content-type: application/json

{
    "nombres": "",
    "apellidos": "",
    "dpi": "",
    "telefono": "",
    "idUsuario": 1
}

###     ACTUALIZAR REGISTRO COBRADOR
PUT  http://localhost:8000/api/cobradores/1
content-type: application/json

{
    "nombres": "perrote",
    "apellidos": "bedoya",
    "dpi": "3201526770501",
    "telefono": "78893212"
}
###     OBTENER CLIENTES POR ID DE COBRADOR
GET http://localhost:8000/api/cobradores/1/clientes


###                                                 RUTAS ENDPOINTS
GET http://localhost:8000/api/rutas

### CREAR RUTA
POST http://localhost:8000/api/rutas
content-type: application/json

{
    "nombreRuta": "",
    "idSede": ,
    "idMunicipio": ,
}

### CREAR RUTA
PUT http://localhost:8000/api/rutas/1
content-type: application/json

{
    "nombreRuta": "",
    "idSede": ,
    "idMunicipio": ,
}


###                                                 PRESTAMOS ENDPOINTS

GET http://localhost:8000/api/prestamos/3/detail





###                                                 CLIENTES ENDPOINTS

###
GET http://localhost:8000/api/clientes/prestamos/1
