GET {{hostname}}/api/prestamos

### CREAR RUTA
POST {{hostname}}/api/prestamos
content-type: application/json

{
}

### CREAR RUTA
PUT {{hostname}}/api/prestamos/1
content-type: application/json

{
}
