GET {{hostname}}/api/prestamos/42

###
GET {{hostname}}/api/prestamos/ruta/1

### CREAR RUTA
POST {{hostname}}/api/prestamos
content-type: application/json

{
}

### CREAR RUTA
PUT {{hostname}}/api/prestamos/1
content-type: application/json

{
}
