GET {{hostname}}/api/usuarios

### CREAR RUTA
POST  {{hostname}}/api/login
content-type: application/json

{
    "username":"perromon",
    "psw":"psdsdsdsds"
}

### CREAR RUTA
PUT {{hostname}}/api/usuarios/1
content-type: application/json

{
}
